version: '3.8'
services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ~/.aws:/root/.aws:ro
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
