apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Chart.Name | lower }}
  {{- if .Values.role_arn }}
  annotations: 
    eks.amazonaws.com/role-arn: {{ .Values.role_arn }}
  {{- end}}
automountServiceAccountToken: true