apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name | lower }}
  labels:
    app: {{ .Chart.Name | lower }}
    env: {{ .Values.environment }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Chart.Name | lower }}
  {{- if (eq .Values.oldapps true) }}
  ports:
    - name: tcp
      protocol: TCP
      port: {{ .Values.service.ports.containerport }}
  {{- else}}
  ports:
    - name: http
      protocol: {{ .Values.service.ports.protocol }}
      port: 80
      targetPort: http
  {{- end}}
  
    
      
  